---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    csvfile: "{{ lookup('file', 'importfiles/tags.csv') }}"
  tasks:
    - name: Parse CSV To YAML
      template:
        src: "./templates/iterate_tags.csv.j2"
        dest: "./netboximport/import_tags.yml"
      run_once: true